package com.yjpapp.stockportfolio.network.model

data class Price
    (var quoteSourceName: String,
     var regularMarketOpen: RegularMarketOpen,
     var averageDailyVolume3Month: AverageDailyVolume3Month,
     var exchanger: String,
     var regularMarketTime: Int,
     var volume24Hr: Volume24Hr,
     var regularMarketDayHigh: RegularMarketDayHigh,
     var shortName: String,
     var averageDailyVolume10Day: AverageDailyVolume10Day,
     var longName: String,
     var regularMarketChange: RegularMarketChange,
     var currencySymbol: String,
     var regularMarketPreviousClose: RegularMarketPreviousClose,
//     private var postMarketTime: Int,
     var preMarketPrice: PreMarketPrice,
     var exchangeDataDelayedBy: Int,
     var toCurrency: String,
     var postMarketChange: PostMarketChange,
     var postMarketPrice: PostMarketPrice,
     var exchangeName: String,
     var preMarketChange: PreMarketChange,
     var circulatingSupply: CirculatingSupply,
     var regularMarketDayLow: RegularMarketDayLow,
     var priceHint: PriceHint,
     var currency: String,
     var regularMarketPrice: RegularMarketPrice,
     var regularMarketVolume: RegularMarketVolume,
     var lastMarket: LastMarket,
     var regularMarketSource: String,
     var openInterest: OpenInterest,
     var marketState: String,
     var underlyingSymbol: UnderlyingSymbol,
     var marketCap: MarketCap,
     var quoteType: String,
     var volumeAllCurrencies: VolumeAllCurrencies,
     var postMarketSource: String,
     var strikePrice: StrikePrice,
     var symbol: String,
//     private var postMarketChangePercent: PostMarketChangePercent,
//     private var preMarketSource: String,
     var maxAge: Int,
     var fromCurrency: FromCurrency,
     var regularMarketChangePercent: RegularMarketChangePercent
     )