package com.yjpapp.stockportfolio.network.model

data class Price
    (private var quoteSourceName: String,
     private var regularMarketOpen: RegularMarketOpen,
     private var averageDailyVolume3Month: AverageDailyVolume3Month,
     private var exchanger: String,
     private var regularMarketTime: Int,
     private var volume24Hr: Volume24Hr,
     private var regularMarketDayHigh: RegularMarketDayHigh,
     private var shortName: String,
     private var averageDailyVolume10Day: AverageDailyVolume10Day,
     private var longName: String,
     private var regularMarketChange: RegularMarketChange,
     private var currencySymbol: String,
     private var regularMarketPreviousClose: RegularMarketPreviousClose,
//     private var postMarketTime: Int,
     private var preMarketPrice: PreMarketPrice,
     private var exchangeDataDelayedBy: Int,
     private var toCurrency: String,
     private var postMarketChange: PostMarketChange,
     private var postMarketPrice: PostMarketPrice,
     private var exchangeName: String,
     private var preMarketChange: PreMarketChange,
     private var circulatingSupply: CirculatingSupply,
     private var regularMarketDayLow: RegularMarketDayLow,
     private var priceHint: PriceHint,
     private var currency: String,
     private var regularMarketPrice: RegularMarketPrice,
     private var regularMarketVolume: RegularMarketVolume,
     private var lastMarket: LastMarket,
     private var regularMarketSource: String,
     private var openInterest: OpenInterest,
     private var marketState: String,
     private var underlyingSymbol: UnderlyingSymbol,
     private var marketCap: MarketCap,
     private var quoteType: String,
     private var volumeAllCurrencies: VolumeAllCurrencies,
     private var postMarketSource: String,
     private var strikePrice: StrikePrice,
     private var symbol: String,
//     private var postMarketChangePercent: PostMarketChangePercent,
//     private var preMarketSource: String,
     private var maxAge: Int,
     private var fromCurrency: FromCurrency,
     private var regularMarketChangePercent: RegularMarketChangePercent
     )