# Generated by Django 3.2.3 on 2022-10-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userinfo_login_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='reg_date',
            field=models.CharField(default=False, max_length=20, null=True),
        ),
    ]
