# Generated by Django 3.2.3 on 2022-10-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_userinfo_reg_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='reg_date',
        ),
    ]
