# Generated by Django 3.2.3 on 2021-07-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uesr', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoginUser',
            new_name='UserInfo',
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '유저 정보'},
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_id',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_pw',
            new_name='user_name',
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='user_info',
        ),
    ]
