# Generated by Django 3.2.3 on 2021-07-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomenote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
