# Generated by Django 3.2.3 on 2021-08-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_note', '0005_alter_incomenote_selldate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomenote',
            name='sellDate',
            field=models.DateField(),
        ),
    ]
