# Generated by Django 3.2.3 on 2021-08-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_note', '0006_alter_incomenote_selldate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomenote',
            name='gainPercent',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='incomenote',
            name='purchasePrice',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='incomenote',
            name='realPainLossesAmount',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='incomenote',
            name='sellPrice',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
