# Generated by Django 3.2.3 on 2021-07-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_note', '0002_alter_incomenote_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomenote',
            name='sellDate',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
