# Generated by Django 3.2.3 on 2021-08-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_note', '0003_alter_incomenote_selldate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomenote',
            options={'ordering': ['-id'], 'verbose_name': '수익노트 테이블'},
        ),
        migrations.AlterField(
            model_name='incomenote',
            name='sellDate',
            field=models.DateField(),
        ),
    ]
