# Generated by Django 3.2.3 on 2021-07-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_index', models.IntegerField(auto_created=True, db_index=True, primary_key=True, serialize=False)),
                ('user_email', models.CharField(default=False, max_length=20)),
                ('user_name', models.CharField(default=False, max_length=20, null=True)),
            ],
            options={
                'verbose_name': '유저 정보',
                'db_table': 'user_info',
            },
        ),
        migrations.DeleteModel(
            name='LoginUser',
        ),
    ]
