# Generated by Django 3.2.3 on 2021-07-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_index',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
