# Generated by Django 3.2.3 on 2021-07-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userinfo_user_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='login_type',
            field=models.CharField(default=False, max_length=20, null=True),
        ),
    ]
