# Generated by Django 3.2.3 on 2021-07-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userinfo_login_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_email',
            field=models.CharField(default=False, max_length=40),
        ),
    ]
