# Generated by Django 3.2.3 on 2021-10-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userinfo_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='login_type',
            field=models.CharField(default=False, max_length=25, null=True),
        ),
    ]
