# Generated by Django 3.2.3 on 2022-10-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_userinfo_reg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='reg_date',
            field=models.CharField(default='null', max_length=20, null=True),
        ),
    ]
